### ISSUE TITLE
Add carousel messages for each type of user

### ISSUE THREAD

**Issue by kryssym** [tutorbookapp/tutorbook#42] opened 2020-05-08 17:13 UTC
Have an image background carousel with messages geared towards each type of user (Students, teachers and parents). It will give visitors a general idea of the service upon landing.

**Comment by nicholaschiang** [comment] 2020-06-01 22:02
Hmm... @kryssym I'd love to get a mock-up of what type of writing would be on each carousel card.

IMO I think our landing page right now is using the above-the-fold space as well as possible:
1. A header that displays the distinct aspects of Tutorbook.
2. A large CTA title that tells the user exactly what value we add for them (e.g. "Free tutoring" or "Learn from and work with an expert").
3. A search bar as part of that CTA.
4. Featured results showing the smiling faces of our volunteers (we include these for social proof and to provide our visitors with instant value; you can book a tutor within a minute of landing on the site).

Do you still believe this would make our home page better? If so, where would we put such a carousel?

**Comment by kryssym** [comment] 2020-06-01 23:10
just did a quick search on whether or not that is best practice and turns out its not. will have to do some more research before I share ideas and start mocking up. I'm not the best copy writer but I'll see what I can come up with

**Comment by kryssym** [comment] 2020-06-02 22:33
Did we still want the landing page to have messages geared towards parents, students, and teachers/mentors? Here's an example of a voice123.com landing page targeting different users and showing their offers. I think TB's previous landing page had "for parents" "for tutors". Perhaps we should bring that back.
[
<img width="1164" alt="Screen Shot 2020-06-02 at 9 24 08 AM" src="https://user-images.githubusercontent.com/64979981/83576220-1893e380-a4e6-11ea-80a1-0183a80bc897.png">
](url)

**Comment by nicholaschiang** [comment] 2020-07-06 22:02
Yeah, I think I agree @kryssym, we want to tailor the experience towards each user role... then again, we want our main CTA to be super clear: "Search for your perfect tutor/mentor" and not diluted by multiple destinations (like the "For tutors" and "For students" links were doing before).

Not completely sure on the best course of action here, but definitely still open to more suggestions (which is why I'm leaving this open for now).

**Comment by nicholaschiang** [comment] 2020-10-02 03:08
Closing this as it's a duplicate of #62.

**Closed by nicholaschiang** 2020-10-02 03:08 UTC
Labels: category:front-end, priority:p4, type:enhancement, type:question
